-- Procedural memory seed — initial 7 patterns (human:seed)
-- POLICY (ADR 0013): modify only via `make procedural-edit` + PR reviewed by @ibernale
-- DO NOT edit this file directly without opening a PR.

INSERT INTO procedural_patterns (pattern_key, version, content, source, created_at, updated_at, active) VALUES
(
    'output_template:dictamen',
    1,
    '{
        "applies_when": {"output_types": ["dictamen"]},
        "instructions": "## Estructura obligatoria para Dictámenes\n\nUtiliza las siguientes secciones en este orden:\n\n1. **Objeto de consulta** — resume la cuestión planteada en 2-3 frases.\n2. **Marco normativo aplicable** — lista las normas, reglamentos y circulares relevantes con referencia CELEX o BOE.\n3. **Análisis jurídico** — desarrolla el análisis por puntos; cada afirmación normativa lleva cita verificable.\n4. **Conclusión** — respuesta directa y acotada a la consulta.\n5. **Cautelas y limitaciones** — incluye siempre el aviso de borrador IA y la necesidad de validación por jurista cualificado.\n\nLongitud objetivo: 600-1200 palabras."
    }',
    'human:seed',
    '2026-05-11T00:00:00',
    '2026-05-11T00:00:00',
    1
),
(
    'output_template:memo_comite',
    1,
    '{
        "applies_when": {"output_types": ["memo_comite"]},
        "instructions": "## Estructura obligatoria para Memos de Comité\n\nFormato ejecutivo, máximo 1 página (400-600 palabras):\n\n1. **Asunto** — una frase.\n2. **Contexto regulatorio** — 2-3 puntos clave (bullet points).\n3. **Implicaciones para el Grupo** — bullet points, priorizados por urgencia.\n4. **Recomendación** — acción propuesta concreta.\n5. **Nota** — borrador asistido por IA, requiere validación Cumplimiento/Legal.\n\nEvita lenguaje técnico excesivo; el destinatario es el Comité de Dirección."
    }',
    'human:seed',
    '2026-05-11T00:00:00',
    '2026-05-11T00:00:00',
    1
),
(
    'routing:crr_transitional_caveat',
    1,
    '{
        "applies_when": {"keywords": ["CRR III", "CRR3", "transitorio", "transitional", "Basilea IV", "Basel IV", "período transitorio"]},
        "instructions": "## Caveat CRR III — Régimen Transitorio\n\nEsta consulta involucra CRR III (Reglamento (UE) 2024/1623). **Añade siempre** la siguiente advertencia en la sección de Cautelas:\n\n> _Las disposiciones de CRR III contienen un amplio régimen de transición escalonada hasta 2033. Las cifras de requisitos de capital citadas pueden diferir según la fecha de aplicación efectiva y las opciones nacionales ejercidas por los Estados miembros. Verificar el estado de implementación vigente antes de aplicar._"
    }',
    'human:seed',
    '2026-05-11T00:00:00',
    '2026-05-11T00:00:00',
    1
),
(
    'routing:cross_jurisdiction_note',
    1,
    '{
        "applies_when": {"keywords": ["múltiples jurisdicciones", "cross-border", "internacional", "grupo consolidado", "filial"]},
        "instructions": "## Nota — Consulta Multi-Jurisdiccional\n\nCuando la consulta involucra más de una jurisdicción, indica explícitamente:\n- Qué norma prevalece en caso de conflicto (principio de consolidación supervisora ECB/SSM para el Grupo).\n- Si existen diferencias materiales en la transposición de directivas UE entre las jurisdicciones afectadas.\n- Que el análisis cubre el nivel de principios; para aplicación local confirmar con el equipo jurídico de cada jurisdicción."
    }',
    'human:seed',
    '2026-05-11T00:00:00',
    '2026-05-11T00:00:00',
    1
),
(
    'citation:reglamento_ue_format',
    1,
    '{
        "applies_when": {"keywords": ["Reglamento", "CELEX", "UE", "EU", "CRR", "DORA", "MiCA", "SRMR", "BRRD"]},
        "instructions": "## Formato de Cita — Reglamentos UE\n\nUsa el siguiente formato para citar reglamentos de la UE:\n\n`Reglamento (UE) YYYY/NNNN del Parlamento Europeo y del Consejo, de DD de [mes] de YYYY, [nombre] — CELEX:XXXXXRXXXX, art. N`\n\nEjemplo: `Reglamento (UE) 2013/575 (CRR) — CELEX:32013R0575, art. 92(1)(a)`\n\nSiempre incluye el número CELEX para facilitar la verificación en EUR-Lex."
    }',
    'human:seed',
    '2026-05-11T00:00:00',
    '2026-05-11T00:00:00',
    1
),
(
    'citation:circular_bde_format',
    1,
    '{
        "applies_when": {"keywords": ["Circular BdE", "Circular BDE", "Banco de España", "BdE", "BDE", "circular bancaria"]},
        "instructions": "## Formato de Cita — Circulares BdE\n\nUsa el formato: `Circular N/YYYY, de DD de [mes], del Banco de España, [descripción] — BOE núm. NNN, de DD de [mes] de YYYY`\n\nEjemplo: `Circular 2/2016, de 2 de febrero, del Banco de España (NIIF 9 adaptación) — BOE núm. 38, de 13 de febrero de 2016`\n\nVerificar que la circular no haya sido modificada o derogada por una circular posterior antes de citar."
    }',
    'human:seed',
    '2026-05-11T00:00:00',
    '2026-05-11T00:00:00',
    1
),
(
    'quality:mifid_applicability_check',
    1,
    '{
        "applies_when": {"keywords": ["MiFID", "MIFID", "instrumento financiero", "servicio de inversión", "asesoramiento en inversión", "gestión de carteras", "mercado de capitales"]},
        "instructions": "## Check Aplicabilidad MiFID II / MiFIR\n\nEn consultas sobre instrumentos financieros o servicios de inversión, verifica y declara explícitamente:\n1. Si la entidad actúa como empresa de servicios de inversión (ESI) o como entidad de crédito prestando servicios de inversión.\n2. Si el instrumento en cuestión está dentro del ámbito de MiFID II (Directiva 2014/65/UE) — excluidos: depósitos, préstamos, seguros de vida fuera del alcance, divisas spot.\n3. Si aplica el régimen de idoneidad/conveniencia (arts. 25-26 MiFID II) según el tipo de cliente y servicio.\n\nCita MiFIR (Reglamento (UE) 600/2014) cuando la consulta involucre obligaciones de transparencia o reporting."
    }',
    'human:seed',
    '2026-05-11T00:00:00',
    '2026-05-11T00:00:00',
    1
);
